stages:
  - deploy    
  - test
test:
  stage: test
  before_script:
  - curl -sL https://deb.nodesource.com/setup_10.x | bash -
  - apt-get install -y nodejs build-essential
  script:
  - gcc --version
  - node --version
  - npm --version   
  - npm install 
  - npm test
deploy_staging:
  stage: deploy
  environment:
    name: staging
    url: https://igive2-4b34a.firebaseapp.com
  before_script:
  - curl -sL https://deb.nodesource.com/setup_10.x | bash -
  - apt-get install -y nodejs build-essential
  script:
  - gcc --version
  - node --version
  - npm --version   
  - npm install 
  - npm install -g firebase-tools
  - echo Building for environment $ENVIRONMENT ci $CI_ENVIRONMENT_NAME
  - npm run build
  - firebase use --token $FIREBASE_DEPLOY_KEY igive2-4b34a
  - firebase deploy --non-interactive --token $FIREBASE_DEPLOY_KEY --only hosting:igive2-4b34a -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID"
  only:
  - development
